# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # labels actions taken with the github token

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.1

      #this will install Node and npm on Ubuntu
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm ci --prefix ./MonitorApp
      - run: npm install --prefix ./MonitorApp -g @angular/cli > /dev/null
      - run: npm install --prefix ./MonitorApp angular-cli-ghpages
#       - run: npm run build --prefix ./MonitorApp --prod --output-path=dist --base-href="https://treedvz.github.io/MonitorApp"
#       - run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - run: npm run deploy --prefix ./MonitorApp 
